FROM nginx:1.23.2-alpine

# Create certificate files from env variable
COPY server.cer /etc/nginx/server.crt
COPY server.key /etc/nginx/server.key

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Make sure the HTTPS port is exposed
EXPOSE 443

# Run the nginx server
CMD ["nginx", "-g", "daemon off;"]
