FROM nginx:1.23.2-alpine

ARG SERVER_CERTIFICATE
ARG SERVER_KEY

# Create certificate files from env variable
RUN echo $SERVER_CERTIFICATE > /etc/nginx/server.crt
RUN echo $SERVER_KEY > /etc/nginx/server.key

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Make sure the HTTPS port is exposed
EXPOSE 443

# Run the nginx server
CMD ["nginx", "-g", "daemon off;"]
