name: Deploy

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Login to registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: 'Build inference server image'
      run: |
        docker build --label "COMMIT_SHA=${{ github.sha }}" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.INFERENCE_SERVER_IMAGE_NAME }}:${{ github.run_number }} .
        
    - name: 'Push inference server image'
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.INFERENCE_SERVER_IMAGE_NAME }}:${{ github.run_number }}

    - name: 'Setup certs'
      run: |
        cat ${{ secrets.SERVER_CRT }} > server.cer
        cat ${{ secrets.SERVER_KEY }} > server.key

    - name: 'Build nginx image'
      run: |
        docker build --label "COMMIT_SHA=${{ github.sha }}" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-inference:${{ github.run_number }} -f .ci/Dockerfile-nginx .ci/
        
    - name: 'Push nginx image'
      run: |
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-inference:${{ github.run_number }}
        
    - name: 'Render ACI manifest'
      uses: chuhlomin/render-template@204ce622bc2fd5c787ff5ca885ff19fb577e7a41      
      with:
        template: .ci/container.template.yaml
        vars: |
          registryUsername: '${{ secrets.REGISTRY_USERNAME }}'
          registryPassword: '${{ secrets.REGISTRY_PASSWORD }}'
          ipAddress: '${{ secrets.IP_ADDRESS }}'
          image: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.INFERENCE_SERVER_IMAGE_NAME }}:${{ github.run_number }}'
          imageNginx: '${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx-inference:${{ github.run_number }}'
          imageInference: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.INFERENCE_SERVER_IMAGE_NAME }}:${{ github.run_number }}'
        result_path: .ci/container.yaml

    - name: 'Deploy to Azure Container Instances'
      run: |
        az container create -g ${{ secrets.RESOURCE_GROUP }} -f .ci/container.yaml
